### ISSUE TITLE
RepoNameのアピールポイントは高いにも関わらずemptyなバグを角煮

### ISSUE THREAD

**Issue by ryoctrl** [kuruppa0616/VRFantasyShooter#1]
# 問題
VRFantasyShooterというアピールにはうってつけのNameを持つRespositoryなのにも関わらずソースコードが存在していない。

# 解決案

ASAPにniceなsolutionをcommitいただきたい

**Comment by kuruppa0616** [comment]
対応しました💢

**Comment by ryoctrl** [comment]
たくさんのmetaファイルありがとうございます。
